### ISSUE TITLE
Duplicate enhanced relation declaration

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/UD_Polish-LFG#1]
In version 2.2, file `pl_lfg-ud-train.conllu`, line `110325`:

```
1	Przecież	przecież	PART	qub	_	6	advmod	6:advmod|8:advmod|10:advmod|12:advmod|12:advmod	_
```

The same enhanced relation `12:advmod` is defined twice.

**Comment by agnieszka-patejuk** [comment]
Thank you, this is solved now (UD release 2.3).
