### ISSUE TITLE
If word ends with "bym"/"łbym" etc. Number of tokens after lematization is increasing

### ISSUE THREAD

**Issue by kate-kara** [UniversalDependencies/UD_Polish-LFG#3]
If i lematize sentence like this:
doc = nlp("podlinkowałbym stronę, ale tego nie zrobię")
I receive wrong number of tokens. Word "podlinkowałbym " is devided in to 3 words:
```
[
  {
    "id": 1,
    "text": "podlinkował",
    "lemma": "podlinkować",
    "upos": "VERB",
    "xpos": "praet:sg:m1:imperf",
    "feats": "Aspect=Imp|Gender=Masc|Mood=Ind|Number=Sing|SubGender=Masc1|Tense=Past|VerbForm=Fin|Voice=Act",
    "misc": "start_char=0|end_char=11"
  }
]
[
  {
    "id": 2,
    "text": "by",
    "lemma": "by",
    "upos": "AUX",
    "xpos": "qub",
    "feats": "Mood=Cnd",
    "misc": "start_char=11|end_char=13"
  }
]
[
  {
    "id": 3,
    "text": "m",
    "lemma": "być",
    "upos": "AUX",
    "xpos": "aglt:sg:pri:imperf:nwok",
    "feats": "Aspect=Imp|Number=Sing|Person=1|Variant=Short",
    "misc": "start_char=13|end_char=14"
  }
]
```

**Comment by dan-zeman** [comment]
What is wrong about it?

**Comment by kate-kara** [comment]
Lematizing should only lematize the word. So word "podlinkowałbym" after lematization shoudl appear like "podlinkować". Not be splitet to 3 words like in this egzample ("podlinkował", "by", "m"). Lematizing shoudl not affect the number of tokens. Should only transform word to the form of the infinitive, nothing more.

**Comment by dan-zeman** [comment]
In Universal Dependencies, some surface tokens correspond to multiple syntactic words (see [tokenization](https://universaldependencies.org/u/overview/tokenization.html)). Lemmas correspond only to syntactic words, not to surface tokens. Hence you must first do tokenization/word segmentation, then lemmatization.

In your example, the surface token actually corresponds to 3 syntactic words: _podlinkował, by, m_. Lemmatization adds exactly one lemma to each of the three words, so it does not increase the number of words.

**Comment by dan-zeman** [comment]
Although segmentation of syntactic words is not the same process as tokenization (separating punctuation from adjacent words), from the perspective of your issue it is the same thing: if you see "period.", you first separate "period" and ".", then assign a lemma to each of them.
